/**
 * POST /api/billing/checkout
 * Initiate Polar checkout session
 *
 * Note: This route should be handled by BetterAuth Polar plugin
 * This is a fallback/alternative implementation
 */

import { Router, Request, Response, NextFunction } from "express";
import { betterAuthMiddleware } from "@/middleware/betterAuth";
import { AppError } from "@/middleware/errorHandler";

export const billingCheckoutRouter = Router();

billingCheckoutRouter.use(betterAuthMiddleware);

billingCheckoutRouter.post("/checkout", async (req: Request, res: Response, next: NextFunction) => {
  try {
    const user = (req as any).user;
    const { slug, productId } = req.body;

    if (!user || !user.id) {
      throw new AppError("Authentication required", 401);
    }

    // Note: BetterAuth Polar plugin handles checkout
    // This is a fallback - in practice, the frontend should call authClient.checkout()
    // Return checkout URL if needed
    res.status(200).json({
      message: "Checkout initiated",
      // Checkout URL would be generated by BetterAuth Polar plugin
      slug,
      productId,
    });
  } catch (error) {
    if (error instanceof AppError) {
      return next(error);
    }
    next(new AppError("Failed to initiate checkout", 500));
  }
});
