/**
 * POST /api/billing/portal
 * Redirect to Polar customer portal
 *
 * Note: This route should be handled by BetterAuth Polar plugin
 * This is a fallback/alternative implementation
 */

import { Router, Request, Response, NextFunction } from "express";
import { betterAuthMiddleware } from "@/middleware/betterAuth";
import { AppError } from "@/middleware/errorHandler";
import { prisma } from "@/lib/prisma";

export const billingPortalRouter = Router();

billingPortalRouter.use(betterAuthMiddleware);

billingPortalRouter.post("/portal", async (req: Request, res: Response, next: NextFunction) => {
  try {
    const user = (req as any).user;

    if (!user || !user.id) {
      throw new AppError("Authentication required", 401);
    }

    // Get user's Polar customer ID
    const dbUser = await prisma.user.findUnique({
      where: { id: user.id },
      select: { polarCustomerId: true },
    });

    if (!dbUser || !dbUser.polarCustomerId) {
      throw new AppError("No Polar customer found. Please contact support.", 404);
    }

    // Note: BetterAuth Polar plugin handles portal redirect
    // This is a fallback - in practice, the frontend should call authClient.customer.portal()
    // Return portal URL if needed, or redirect
    res.status(200).json({
      message: "Redirect to Polar customer portal",
      // Portal URL would be generated by BetterAuth Polar plugin
    });
  } catch (error) {
    if (error instanceof AppError) {
      return next(error);
    }
    next(new AppError("Failed to access billing portal", 500));
  }
});
