// NodeType enum matching backend schema
export const NodeType = {
  INITIAL: "INITIAL",
  MANUAL_TRIGGER: "MANUAL_TRIGGER",
  TIMED_TRIGGER: "TIMED_TRIGGER",
  HTTP_REQUEST: "HTTP_REQUEST",
  WEBHOOK: "WEBHOOK",
  GOOGLE_FORM_TRIGGER: "GOOGLE_FORM_TRIGGER",
  STRIPE_TRIGGER: "STRIPE_TRIGGER",
  ANTHROPIC: "ANTHROPIC",
  GEMINI: "GEMINI",
  OPENAI: "OPENAI",
  DISCORD: "DISCORD",
  SLACK: "SLACK",
  WHATSAPP_TRIGGER: "WHATSAPP_TRIGGER",
  WHATSAPP: "WHATSAPP",
  DECIDER: "DECIDER",
} as const;

export type NodeTypeValue = (typeof NodeType)[keyof typeof NodeType];
