/**
 * Node type constants matching the Prisma NodeType enum (schema.prisma lines 325-330)
 * Use these constants throughout the codebase to ensure consistency and avoid node type errors
 */
export const NodeType = {
  MANUAL_TRIGGER: "MANUAL_TRIGGER",
  MANUAL_INPUT: "MANUAL_INPUT",
  TIMED_TRIGGER: "TIMED_TRIGGER",
  HTTP_REQUEST: "HTTP_REQUEST",
  WEBHOOK: "WEBHOOK",
  INITIAL: "INITIAL",
  GOOGLE_FORM_TRIGGER: "GOOGLE_FORM_TRIGGER",
  STRIPE_TRIGGER: "STRIPE_TRIGGER",
  ANTHROPIC: "ANTHROPIC",
  GEMINI: "GEMINI",
  OPENAI: "OPENAI",
  DISCORD: "DISCORD",
  SLACK: "SLACK",
  WHATSAPP_TRIGGER: "WHATSAPP_TRIGGER",
  WHATSAPP: "WHATSAPP",
  TELEGRAM_TRIGGER: "TELEGRAM_TRIGGER",
  TELEGRAM: "TELEGRAM",
  DECIDER: "DECIDER",
  GOOGLE_DRIVE: "GOOGLE_DRIVE",
  GOOGLE_CALENDAR: "GOOGLE_CALENDAR",
  GOOGLE_SHEETS: "GOOGLE_SHEETS",
  GOOGLE_DOCS: "GOOGLE_DOCS",
  GOOGLE_MEET: "GOOGLE_MEET",
  GOOGLE_SLIDES: "GOOGLE_SLIDES",
  GMAIL: "GMAIL",
  AIRTABLE: "AIRTABLE",
  AIRTABLE_TRIGGER: "AIRTABLE_TRIGGER",
  ELEVENLABS: "ELEVENLABS",
  FIRECRAWL: "FIRECRAWL",
  APIFY: "APIFY",
  CODE_BLOCK: "CODE_BLOCK",
  PLAN: "PLAN",
  DESIGN: "DESIGN",
  LOYALTY_DEAL: "LOYALTY_DEAL",
  LOYALTY_PROGRAM: "LOYALTY_PROGRAM",
} as const;

export type NodeTypeValue = (typeof NodeType)[keyof typeof NodeType];
