// This file was generated by prisma-field-encryption.

import type { PrismaClient, ChatIntegration } from '../../../client/node_modules/.prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = ChatIntegration['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'ChatIntegration',
    client,
    getTotalCount: client.chatIntegration.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.chatIntegration.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        sharedSecret: true,
        telegramBotToken: true,
        slackBotToken: true,
        slackSigningSecret: true,
        discordBotToken: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.chatIntegration.update({
      where: {
        id: record.id
      },
      data: {
        sharedSecret: record.sharedSecret,
        telegramBotToken: record.telegramBotToken,
        slackBotToken: record.slackBotToken,
        slackSigningSecret: record.slackSigningSecret,
        discordBotToken: record.discordBotToken
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "sharedSecret": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "telegramBotToken": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "slackBotToken": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "slackSigningSecret": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "discordBotToken": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "user": {
 *       "modelName": "User",
 *       "isList": false
 *     },
 *     "externalIdentities": {
 *       "modelName": "ExternalIdentity",
 *       "isList": true
 *     },
 *     "whatsappSession": {
 *       "modelName": "WhatsAppSession",
 *       "isList": false
 *     }
 *   }
 * }
 */
