// This file was generated by prisma-field-encryption.

import type { PrismaClient } from '../../../client/node_modules/.prisma/client'
import { migrate as migrateVerxioUser } from './VerxioUser'
import { migrate as migrateLoyaltyProgram } from './LoyaltyProgram'
import { migrate as migrateLoyaltyPass } from './LoyaltyPass'
import { migrate as migrateVoucherCollection } from './VoucherCollection'
import { migrate as migrateVoucher } from './Voucher'
import { migrate as migrateAccount } from './Account'
import { migrate as migrateCredential } from './Credential'
import { migrate as migrateGoogleOAuthToken } from './GoogleOAuthToken'
import { migrate as migrateChatIntegration } from './ChatIntegration'

export interface ProgressReport {
  model: string
  processed: number
  totalCount: number
  performance: number
}

export type ProgressReportCallback = (
  progress: ProgressReport
) => void | Promise<void>

export const defaultProgressReport: ProgressReportCallback = ({
  model,
  totalCount,
  processed,
  performance
}) => {
  const length = totalCount.toString().length
  const pct = Math.round((100 * processed) / totalCount)
    .toString()
    .padStart(3)
  console.info(
    `${model.padEnd(17)} ${pct}% processed ${processed
      .toString()
      .padStart(length)} / ${totalCount} (took ${performance.toFixed(2)}ms)`
  )
}

// --

export type MigrationReport = {
  VerxioUser: number,
  LoyaltyProgram: number,
  LoyaltyPass: number,
  VoucherCollection: number,
  Voucher: number,
  Account: number,
  Credential: number,
  GoogleOAuthToken: number,
  ChatIntegration: number
}

/**
 * Migrate models sequentially.
 *
 * Processed models:
 * - VerxioUser
 * - LoyaltyProgram
 * - LoyaltyPass
 * - VoucherCollection
 * - Voucher
 * - Account
 * - Credential
 * - GoogleOAuthToken
 * - ChatIntegration
 *
 * @returns a dictionary of the number of processed records per model.
 */
export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<MigrationReport> {
  const processedVerxioUser = await migrateVerxioUser(client, reportProgress)
  const processedLoyaltyProgram = await migrateLoyaltyProgram(client, reportProgress)
  const processedLoyaltyPass = await migrateLoyaltyPass(client, reportProgress)
  const processedVoucherCollection = await migrateVoucherCollection(client, reportProgress)
  const processedVoucher = await migrateVoucher(client, reportProgress)
  const processedAccount = await migrateAccount(client, reportProgress)
  const processedCredential = await migrateCredential(client, reportProgress)
  const processedGoogleOAuthToken = await migrateGoogleOAuthToken(client, reportProgress)
  const processedChatIntegration = await migrateChatIntegration(client, reportProgress)
  return {
    VerxioUser: processedVerxioUser,
    LoyaltyProgram: processedLoyaltyProgram,
    LoyaltyPass: processedLoyaltyPass,
    VoucherCollection: processedVoucherCollection,
    Voucher: processedVoucher,
    Account: processedAccount,
    Credential: processedCredential,
    GoogleOAuthToken: processedGoogleOAuthToken,
    ChatIntegration: processedChatIntegration
  }
}
