// This file was generated by prisma-field-encryption.

import type { PrismaClient, LoyaltyProgram } from '../../../client/node_modules/.prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = LoyaltyProgram['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'LoyaltyProgram',
    client,
    getTotalCount: client.loyaltyProgram.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.loyaltyProgram.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        programSecretKey: true,
        authoritySecretKey: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.loyaltyProgram.update({
      where: {
        id: record.id
      },
      data: {
        programSecretKey: record.programSecretKey,
        authoritySecretKey: record.authoritySecretKey
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "programSecretKey": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "authoritySecretKey": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "claimLinks": {
 *       "modelName": "LoyaltyClaimLink",
 *       "isList": true
 *     }
 *   }
 * }
 */
