// This file was generated by prisma-field-encryption.

import type { PrismaClient, LoyaltyPass } from '../../../client/node_modules/.prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = LoyaltyPass['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'LoyaltyPass',
    client,
    getTotalCount: client.loyaltyPass.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.loyaltyPass.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        loyaltyPassPrivateKey: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.loyaltyPass.update({
      where: {
        id: record.id
      },
      data: {
        loyaltyPassPrivateKey: record.loyaltyPassPrivateKey
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "loyaltyPassPrivateKey": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {}
 * }
 */
