// This file was generated by prisma-field-encryption.

import type { PrismaClient, VerxioUser } from '../../../client/node_modules/.prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = VerxioUser['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'VerxioUser',
    client,
    getTotalCount: client.verxioUser.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.verxioUser.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        creatorPrivateKey: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.verxioUser.update({
      where: {
        id: record.id
      },
      data: {
        creatorPrivateKey: record.creatorPrivateKey
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "creatorPrivateKey": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "sentTransactions": {
 *       "modelName": "VerxioTransaction",
 *       "isList": true
 *     },
 *     "receivedTransactions": {
 *       "modelName": "VerxioTransaction",
 *       "isList": true
 *     },
 *     "apiKeys": {
 *       "modelName": "ApiKey",
 *       "isList": true
 *     }
 *   }
 * }
 */
