// This file was generated by prisma-field-encryption.

import type { PrismaClient, VoucherCollection } from '../../../client/node_modules/.prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = VoucherCollection['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'VoucherCollection',
    client,
    getTotalCount: client.voucherCollection.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.voucherCollection.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        collectionSecretKey: true,
        authoritySecretKey: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.voucherCollection.update({
      where: {
        id: record.id
      },
      data: {
        collectionSecretKey: record.collectionSecretKey,
        authoritySecretKey: record.authoritySecretKey
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "collectionSecretKey": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "authoritySecretKey": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "vouchers": {
 *       "modelName": "Voucher",
 *       "isList": true
 *     },
 *     "rewardLinks": {
 *       "modelName": "RewardLink",
 *       "isList": true
 *     }
 *   }
 * }
 */
